### PR TITLE
go.mod: upgrade dependencies and rid vulnerable thrift version@v0.12.0

### PR DESCRIPTION
**Pull request by odeke-em**
Coming here, after digging through
google/exposure-notifications-server#749
in which the version of github.com/apache/thrift was reported by
@whaber as having known critical vulnerabilities.

Transitively however, this version was pinning to
cloud.google.com/go@v0.37.4 indirectly, which then imported
versions of opencensus:
* go.opencensus.io@v0.19.
* go.opencensus.io@v0.20.1
that imported
    github.com/apache/thrift@v0.12.0

### CODE REVIEW

**Comment by odeke-em** [comment]
Thanks @dhui for the initial review! I've made a  conservative update to only github.com/denisenkom/go-mssqldb@v0.0.0-20200620013148-b91950f658ec which then doesn't touch the Gitlab client. Let's see if that works.

**Comment by odeke-em** [comment]
Thank you for the merge! Please help cut a  release that’ll then be used by
various go.mod dependent projects. Thank you.

**Comment by dhui** [comment]
Done: [v4.12.0](https://github.com/golang-migrate/migrate/releases/tag/v4.12.0)

**Pull request merged**
