### PR TITLE
[sqlserver] Ensure version table in provided schema

### LINKED ISSUE #839: [sqlserver] `ensureVersionTable()` errors with custom schema
When using a default DB schema other than `dbo`, the `ensureVersionTable()` method errors.

**Steps to Reproduce**
1. Create a user with default schema other than `dbo`: `CREATE USER foo WITH PASSWORD = 'pw', DEFAULT_SCHEMA = [my_schema];`
2. Open connection to database: `dbDriver, err := sqlserver.WithInstance(db, &sqlserver.Config{SchemaName: "my_schema",MigrationsTable: "schema_migrations",})`
3. When trying to open the connection a second time, the error occurs.

**Expected Behavior**
The method should either check for the version table in the given schema name **OR** always create the version table in the `dbo` schema.

**Migrate Version**
v4.15.2

**Loaded Source Drivers**
n.a

**Loaded Database Drivers**
sqlserver

**Go Version**
go1.19.2 darwin/arm64

**Stacktrace**
```
could not load migrations: could not create migration: could not create DB driver from instance: mssql: There is already an object named 'schema_migrations' in the database. in line 0: IF NOT EXISTS
	(SELECT *
		 FROM sysobjects
		WHERE id = object_id(N'[dbo].[schema_migrations]')
			AND OBJECTPROPERTY(id, N'IsUserTable') = 1
	)
	CREATE TABLE schema_migrations ( version BIGINT PRIMARY KEY NOT NULL, dirty BIT NOT NULL );
```

### PR DESCRIPTION
**Pull request by alex-kuck**
Closes #839

### CODE REVIEW

**Comment by alex-kuck** [comment]
@dhui @Fontinalis Do you agree with this solution, or would you prefer to always create the version table in schema `dbo` instead?

**Comment by germanozambelli** [comment]
Is there any news? I too need this PR to be merged

**Review by germanozambelli — APPROVED** [review]

**Review by germanozambelli — APPROVED** [review]

**Comment by zhenriquegomes** [comment]
Any news about this PR?

**Comment by alex-kuck** [comment]
Rebased and fixed linter issues, so should be good to go 🤞

**Review by zhenriquegomes — APPROVED** [review]

**Comment by alex-kuck** [comment]
@dhui Sorry to bother you personally, but is there anything I/we can do to get this merged? Thanks! 🙏

**Review by dhui — COMMENTED** [review]
@alex-kuck Thanks for the PR and sorry for the delayed response!
Overall, I'm onboard with having the schema migration version table stored with the custom schema since this allows multiple projects/apps to use golang-migrate with a single sqlserver.
Is this change backwards compatible? e.g. what happens with existing db instances that use a custom schema? I believe that the "old" migration version table would be stored in `dbo` but after this change, golang-migrate would now expect it to be in the custom schema.

**Comment by alex-kuck** [comment]
Hi @dhui, thanks for your review and no worries, I'm just happy to get this one out the door 😄
I don't think this would be an issue. I believe in the current implementation - i.e. pre-PR - the schema `dbo` is only explicitly used for existence check of the migration table. All other access - including the actual creation - uses the default schema of the connection (i.e. without explicit schema specification). So I think there are basically three cases:

1. User has no default schema and no schema is set in config -> SQL Server default `dbo` is used everywhere. So migration table was created there and will still be used from there after the PR
2. User has default schema `dbo` and/or config schema is explicitly set to `dbo` -> same as 1.
3. User has different default schema `xyz` and/or different schema is set in config -> migration table is still in `xyz` *but* error described in issue will no longer occur, since existence check uses `xyz`

Hope this makes sense 😅

**Review by dhui — APPROVED** [review]
@alex-kuck Thanks again for the PR and your patience!
Also thanks for answering my questions and enumerating the various scenarios. It looks like custom schemas weren't supported by the sqlserver db driver before this PR. It looks like this was a bug with the initial implementation where the `dbo` schema was explicitly specified in the migration table existence check but not any other usage.

**Pull request merged**
