### PR TITLE
Fix builds

### PR DESCRIPTION
**Pull request by dhui**
Multiple changes are need to fix builds, so batching them up in this branch

### CODE REVIEW

**Comment by joschi** [comment]
@dhui I've also been (successfully 😅) trying to get the build back to green:

- https://github.com/golang-migrate/migrate/pull/1128
- https://github.com/golang-migrate/migrate/pull/1126
- https://github.com/golang-migrate/migrate/pull/1127
- https://github.com/golang-migrate/migrate/pull/1133

All these PRs have a successful CI workflow.

**Comment by dhui** [comment]
@joschi Thanks for all of your efforts to fix builds! I've isolated the failing test (redshift) and have a better fix for it (e.g. doesn't run a forked container). If you'd like, I can push just the redshift test fix, you can rebase your changes, and we can merge your changes so you get credit.

**Comment by joschi** [comment]
> e.g. doesn't run a forked container

The reason why I cloned the original `postgres:8` Docker image instead of bumping to the latest PostgreSQL version (and updating the test) is that Amazon Redshift is a fork of PostgreSQL 8.x and PostgreSQL 16 might contain features or behave slightly different than Redshift.

Of course this is still an imperfect test abstraction but given that copying/cloning the image was a one-time thing, I think it makes sense going this way.

What do you think?

**Comment by dhui** [comment]
> > e.g. doesn't run a forked container
> 
> The reason why I cloned the original `postgres:8` Docker image instead of bumping to the latest PostgreSQL version (and updating the test) is that Amazon Redshift is a fork of PostgreSQL 8.x and PostgreSQL 16 might contain features or behave slightly different than Redshift.
> 
> Of course this is still an imperfect test abstraction but given that copying/cloning the image was a one-time thing, I think it makes sense going this way.
> 
> What do you think?

@joschi Thanks for calling this out! I downgraded the redshift tests to use pg8 and tests pass now. This may be short-lived since I got a deprecation warning about the image format version. I'm not opposed to forking the postgres:8 docker image but would like that fork to live in the golang-migrate org for security purposes.

**Comment by joschi** [comment]
> but would like that fork to live in the golang-migrate org for security purposes

Perfectly understandable and I would do the same thing. 😅 

The README in https://hub.docker.com/r/joschi/postgres8 describes how the image was pushed.

If you're logged into Docker Hub locally with permissions to push to the [migrate](https://hub.docker.com/u/migrate) organization, you can use these commands to clone the image with updated manifest versions:
```text
# docker pull postgres:8
# docker tag postgres:8 migrate/postgres8:8
# docker push migrate/postgres8:8

# docker pull postgres:8.4
# docker tag postgres:8.4 migrate/postgres8:8.4
# docker push migrate/postgres8:8.4

# docker pull postgres:8.4.22
# docker tag postgres:8.4.22 migrate/postgres8:8.4.22
# docker push migrate/postgres8:8.4.22
```

**Comment by dhui** [comment]
Closing in favor of @joschi's PRs. Thanks @joschi for your help and patience in fixing builds and updating dependencies!

**Pull request closed without merging**
