### PR TITLE
Refactor cli package to allow `go get` one-liner with a proper binary name

### PR DESCRIPTION
**Pull request by vearutop**
Fixes https://github.com/golang-migrate/migrate/issues/70.

* Copy cli main package under migrate directory,
* Keep deprecated original main package for backwards compatibility

### CODE REVIEW

**Comment by vearutop** [comment]
Maybe it also makes sense to move common cli package under root `internal` to protect it from being used by 3rd party.

**Comment by dhui** [comment]
I like the `internal` package idea!
e.g. `migrate/cli/internal` instead of `migrate/cli/cli`
I think it's fine to make the move in this PR since the code's already being moved and there's no breakage of backwards compatibility since [nothing is exported](https://godoc.org/github.com/golang-migrate/migrate/cli)

**Comment by dhui** [comment]
> That has to be ./internal/cli (not ./cli/internal) to be accessible for ./cmd/migrate, is that ok?

Oh yeah, forgot about that. Yep, `migration/internal/cli` is fine.

**Comment by vearutop** [comment]
@dhui please check latest commit if you have any other change requests.

**Comment by dhui** [comment]
Thanks for contributing @vearutop !

**Comment by eleijonmarck** [comment]
How would one be able to install the cli library only to be used in a docker image.

So I would like to compile `cmd/migrate` to a binary called `migrate`
and use the binary for migrations.

is this possible? If so how?

**Pull request merged**
