### PR TITLE
goreleaser configuration and automatic release workflow

### LINKED ISSUE #74: Use GoReleaser for releases
Supports a lot out of the box that we don't have to maintain and should make the release process easier.

### Features:
* Integrates with Travis: https://goreleaser.com/ci/
* Handles pushing Docker images: https://goreleaser.com/customization/#Docker
* Auto-generates changelog (can be customized): https://goreleaser.com/customization/#Release
* Only supports pushing to custom homebrew taps: https://goreleaser.com/customization/#Homebrew
* Checksums for binaries: https://goreleaser.com/customization/#Checksum
* Signed releases: https://goreleaser.com/customization/#Signing
    * May not sign releases as we'd have to give TravisCI the private key: https://stackoverflow.com/questions/45188811/how-to-gpg-sign-a-file-that-is-built-by-travis-ci
* Doesn't depend on fpm (uses nfpm instead): https://goreleaser.com/customization/#NFPM
    * Not sure if this is good or bad...

### PR DESCRIPTION
**Pull request by johejo**
close #74 

## Required settings

GitHub Actions secrets
- DOCKERHUB_USERNAME
- DOCKERHUB_PASSWORD
- PACKAGECLOUD_TOKEN

## How to release

I imagined as much as possible what the existing release workflow would look like, and followed the steps below.
If you don't like it, please send comments.
We can also automatically generate a change log for the release notes.

1. push a new tag (manual)
2. publish draft release (automatic)
3. edit draft release and publish release (manual)

### CODE REVIEW

**Review by dhui — COMMENTED** [review]
I'm still not completely sold on using GitHub Actions over CircleCI (even though CircleCI is currently having an outage as I write this).

Do you have a preference of GitHub Actions over CircleCI and why?

Are there [additional tools](https://github.com/golang-migrate/migrate/pull/521#issuecomment-798960578) you need to install to use buildx that's more cumbersome with CircleCI? I noticed you were [using qemu](https://github.com/docker/setup-buildx-action#with-qemu).

**Comment by johejo** [comment]
Here's why I chose GitHub Actions:

- The official action makes it easy to set up buildx and qemu needed to build a docker image for multiple architectures. It's certainly possible with CircleCI. But it seems complicated. https://circleci.com/blog/building-docker-images-for-multiple-os-architectures/
- Default GITHUB_TOKEN available, No additional PAT setting is required for new release workflow.
- I used it in my daily work and was used to it.

If the maintainer decides that CircleCI is preferable for some reasons, I'll remove the workflow config file from this PR once because I'm not familiar with CirtcleCI.

I might try another PR.
It seems that Arm instance is also available on CircleCI.
https://circleci.com/changelog/#arm-compute-now-generally-available

**Comment by dhui** [comment]
This PR should also unblock releases: https://github.com/golang-migrate/migrate/pull/570

**Comment by dhui** [comment]
Sorry for the delayed response!

Can you modify this to use CircleCI?
My concern with Github Actions is the [2K action minutes limit](https://docs.github.com/en/github/getting-started-with-github/learning-about-github/githubs-products#github-free-for-organizations):
> GitHub Actions limits

**Comment by Juneezee** [comment]
> Sorry for the delayed response!
> 
> Can you modify this to use CircleCI?
> My concern with Github Actions is the [2K action minutes limit](https://docs.github.com/en/github/getting-started-with-github/learning-about-github/githubs-products#github-free-for-organizations):
> 
> > GitHub Actions limits

The 2K limit only applies to private repositories.

**Comment by dhui** [comment]
@Juneezee See the link and attached screenshot in my [original comment](https://github.com/golang-migrate/migrate/pull/570#issuecomment-850675163). It shows 2k action minutes for "Github Free for organizations"

**Comment by Juneezee** [comment]
> @Juneezee See the link and attached screenshot in my [original comment](https://github.com/golang-migrate/migrate/pull/570#issuecomment-850675163). It shows 2k action minutes for "Github Free for organizations"

I can't stress this enough. It has been clearly stated here (https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions) that GitHub Actions is **free for public repositories**. Those minutes limit you are seeing only applies for private repositories.

If you still don't believe me, you can go to the Billing & Plans section of golang-migrate organization. Under the Usage This Month, the 2K limit is clearly labelled for **private** repositories only.

**Comment by dhui** [comment]
Ahh, thanks for the pointer @Juneezee! I can see that the minutes are only tracked for private repos:
> 
github actions billing

**Comment by xrn** [comment]
Hi, any progress on this? Are we able to enable the release process of this repository one more time?

**Comment by hfuss** [comment]
Would love to see this (or something like it) merged soon, I was using the `migrate/migrate:latest` Docker image to pull migrations from a public GH repo and got:
```
error: no username:token provided
```
which (after some time) I found was fixed in https://github.com/golang-migrate/migrate/pull/501 which is why the docs say it works so I was very confused. The lack of a CI process currently is hurting the usability of the CLI/image.

I'm fine with pushing a temporary image of the latest commit from master to our internal registry but would really like to not have to maintain that in the long-run.

**Comment by hfuss** [comment]
FWIW we just chose GitHub Actions and GHCR for the CI and container registry of our open-source project https://github.com/hyperledger-labs/firefly due to the free build minutes for public repos, growing ecosystem of actions and features, CI being directly integrated into SCM is a great dev experience, and the lack of (relative to DockerHub) image pull rate-limiting.

Perhaps as a follow up to this PR being merged, the image can be migrated from DockerHub to GHCR.

**Comment by johejo** [comment]
See #604, thanks @Fontinalis

**Pull request closed without merging**
