### PR TITLE
Add "always up" capability

### PR DESCRIPTION
**Pull request by sprak3000**
## What

This adds detection of the file pattern `*.alwaysup.sql` and `*.alwaysdown.sql`. These files will be executed every time the migration tool is used.

## Why

This is useful for migrations that setup items like stored procedures, custom data types, and other persistent objects. Here is a sample use case.

A developer writes a stored procedure and needs to alter its body a month later. Under normal use, the developer would need to write a new migration file to have the changes applied. This makes it difficult for other developers to review what has changed or see the overall history behind the procedure.

Using the `alwaysup` filename, the procedure can be developed within the same file allowing for version control systems to do diffs during PR reviews, show the history of the file, etc.

### CODE REVIEW

**Comment by dhui** [comment]
How would versioning `alwaysup` migrations work? e.g. how would you know which version of the `alwaysup` migration was applied?

What's the use case for `alwaysdown`?

**Comment by sprak3000** [comment]
> How would versioning `alwaysup` migrations work? e.g. how would you know which version of the `alwaysup` migration was applied?

You would have no schema based way of tracking that. That becomes a concern of your version control system. The concept behind it is this. Let's say you have a stored proc looking like this:

```sql
CREATE OR REPLACE FUNCTION get_foo(id UUID, options VARCHAR[])
    RETURNS thing AS
$$
DECLARE
    ret   thing;
BEGIN
-- 50+ lines of code...

    IF COALESCE(array_length(stuff, 1), 0) = 0 THEN
        PERFORM throw_stuff_required();
    END IF;

-- 50+ more lines of code...
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
``` 

Dev goes to change the exception thrown. Under normal circumstances, the dev has to write a new migration containing this:

```sql
CREATE OR REPLACE FUNCTION get_foo(id UUID, options VARCHAR[])
    RETURNS thing AS
$$
DECLARE
    ret   thing;
BEGIN
-- 50+ lines of code...

    IF COALESCE(array_length(stuff, 1), 0) = 0 THEN
        PERFORM throw_stuff_missing();
    END IF;

-- 50+ more lines of code...
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
``` 

Anyone trying to review a PR either has to read and parse the 100+ lines of SQL again or spend time searching through the migration files to find the last version of the proc. An always up file means you keep editing the same file time and again. The PR diff for the change above becomes one easy line to read. You can look back through VCS history to see previous states.

It is an enhancement with a trade off. Developer convenience for tracking and reviewing proc changes at the cost of not having the version of the proc tracked by the tool's schema.

> What's the use case for `alwaysdown`?

I can't say we've come across a use case for them ourselves, but the idea is the same as always up. We always want to do something -- create / recreate a stored proc, etc. -- when we run migrations forward. Likewise, there may be clean up we want to do when we roll back a migration. Maybe that's inserting data into a custom tracking table. Maybe it is cleaning up rows.

**Comment by dhui** [comment]
You can still diff migration files against each other e.g.
```bash
$ arr=(*_my_stored_procedure_migration.up.sql)
$ diff -u ${arr[-2]} ${arr[-1]}
```
But I don't think there's any easy way to do this in GitHub or whatever hosted web-based git solution you're using.

I'm not sure if this convenience is worth the complexity of adding another migration type/direction (e.g. `alwaysup`) and constantly overwriting a stored procedure doesn't seem elegant.
How often is your team modifying a stored procedure?

**Comment by sprak3000** [comment]
> You can still diff migration files against each other e.g.
<snip>
> But I don't think there's any easy way to do this in GitHub or whatever hosted web-based git solution you're using.

Exactly. It forces a developer to have to step out of their normal flow and take extra steps to accomplish their task. Imagine I opened this PR, and the nearly 1000 lines of code in `migrate.go` showed up as new. "Hey, I know this file isn't new. What's just the change you made?" "Oh, go look through this S3 bucket of files, find the right one, and use some other tool to compare."

You now have two processes in place for approving code changes, one that takes you entirely out of the normal flow and is uncertain. Is this stored proc entirely new? Don't know... Going to have to search through the migration files for the latest version and then manually diff. Come back to GitHub to make comments.

There is also the use case of one dev working on adding new functionality to the proc while another is fixing a bug. Two PRs go up at the same time and are looked at by different devs. Both get approved and merged in. Latest migration file is going to win meaning either the bug fix or the new functionality is going to get lost.

> I'm not sure if this convenience is worth the complexity of adding another migration type/direction (e.g. `alwaysup`) and constantly overwriting a stored procedure doesn't seem elegant.
> How often is your team modifying a stored procedure?

It varies. Not often once the initial churn of development, fixing bugs found in production happens. That said, it has been invaluable to be able to easily see the diff in some of our larger stored procs when they go up in a PR. This is especially true when we are onboarding new team members; it is one less process to have to teach them. And, we have definitely had the scenario above of one person fixing a bug while another is adding new functionality to a proc occur.

Best case I can make is this behavior is optional. It is an enhancement to the tool people (like me and my team 😄 ) can make use of. Happy to bury it deeper in the docs to avoid any initial confusion for new users of the tool.

**Comment by Fontinalis** [comment]
I'm in favor of the idea here, I'd love the `version__name.alwaysup.ext` functionality. I have projects where I have hundreds of migration files and some of them are just fixes of a function with a complex calculation in it. In each fix, it would be awesome if I could just update one single migration and just see the exact changes I made without any additional `diff` command. And for updates it does make sense.

For `alwaysdown`, I can't see the point though. You have a `95_something.alwaysdown.sql` and you are at version `100`. You downgrade to `90` and your

**Comment by svekko** [comment]
Just to add in to the discussion:

I'm not sure it's quite correct to define constantly changing database procedures, views, etc. in migration files at all. 

Perhaps you can store these kind of things in a separate directories. For example, single directory for `migrations`, single directory for `pre-migrations` (extensions, trigger procedures, etc.) and single directory for `post-migrations` (procedures, views, etc.)

And then handle them separately from migrations using whatever database driver you are using.

**Comment by sprak3000** [comment]
@svekko 

> I'm not sure it's quite correct to define constantly changing database procedures, views, etc. in migration files at all.

I would be interested in hearing more what you feel is not quite correct about it. One way to view it is I am migrating from an old definition of a stored procedure to a new one.

> Perhaps you can store these kind of things in a separate directories. For example, single directory for `migrations`, single directory for `pre-migrations` (extensions, trigger procedures, etc.) and single directory for `post-migrations` (procedures, views, etc.)
> 
> And then handle them (`pre-migrations` and `post-migrations`) separately from migrations using whatever database driver you are using.

Feels unnecessary to have to use two different tools that essentially serve the same purpose -- execute SQL files in some order. The added functionality here is "Run these specific files all the time. Do not track them as you normally would". That said, maybe a more palatable change to the community would be a CLI flag / switch saying "Don't track the version on these"? Then, I could separate the files into directories like you suggest but run the tool with that flag / switch on or off based on what directory I use.

**Comment by svekko** [comment]
@sprak3000 

> I would be interested in hearing more what you feel is not quite correct about it. One way to view it is I am migrating from an old definition of a stored procedure to a new one.

Okay. As i understand you have defined `alwaysup` migration files with same format as default `up` migrations, so there is always a version defined. And version 5 `alwaysup` migration will always be run before version 7 `up` migration, though that `alwaysup` migration will be run even if version 7 `up` migration (or the version `5` itself) has already been applied. 

What happens if you have a view defined in that version 5 `alwaysup` migration and that version 7 `up` migration introduces a new column to the table used in a view in version `5`? You'd like to introduce that column in that view as well, but you can not - if version `7` has not been run yet, adding that column in the migration version `5` would fail, because the column has not been added yet.

**Comment by sprak3000** [comment]
> What happens if you have a database view defined in that version 5 `alwaysup` migration and that version 7 `up` migration introduces a new column to the table used in a view in version `5`? You'd like to introduce that column in that view as well, but you can not - if version `7` has not been run yet, adding that column in the migration version `5` would fail, because the column has not been added yet.

That is a possibility with or without an always up feature. I could have devs working on the code base simultaneously and check in migration files that won't work in the specific order they used. They and / or the CI pipeline would need to detect that the migrations either failed outright or didn't produce the schema expected and adjust the migrations accordingly. The adjustment in your scenario would be to reorder the view migration file to a higher number. Our team has always up files start at a very high number to ensure schema changes are run first.

Are there pitfalls / gotchas to this concept? Yes, but this is an optional feature -- either in the form of the filename detections I have proposed here or potentially moving to a flag to ignore versioning for a particular run. I've had this use case come up at a few places now, hence this PR. 🤷🏽

**Comment by jwhitaker-swiftnav** [comment]
Came here looking for exactly this functionality, this is a feature in other tooling and my use case is very similar to what @sprak3000 said: I want to define certain things declaratively and not with explicit version files.

The benefits of doing this outweigh the fact I then need to be careful that my "always" migrations might run on a different database layout that when they were written.

**Comment by sprak3000** [comment]
@jwhitaker-swiftnav 

If you are interested, we have our ["always up" fork](https://github.com/HqOapp/migrate) publicly available. I strive to keep it up to date with this upstream repo. Things like the CircleCI and docker configs diverge slightly to accommodate my company's specific needs in those areas, but the core functionality is kept in line just with the always up modifications available.

Hope that helps.

**Pull request closed without merging**
