### PR TITLE
[704] Got error on apply clickhouse migrations from code

### PR DESCRIPTION
**Pull request by sergey-telpuk**

### CODE REVIEW

**Comment by sergey-telpuk** [comment]
#707

**Comment by makeavish** [comment]
@sergey-telpuk When is it going to get merged?

**Comment by sergey-telpuk** [comment]
> @sergey-telpuk When is it going to get merged?

I'm glad to do it, but I need to get the  approve

**Comment by makeavish** [comment]
@dhui Please review this PR

**Comment by dhui** [comment]
Can you link to docs where binding with `?` breaks? Substituting directly is more dangerous since it's prone to injections. I'd rather wait for the underlying db driver to fix their binding issues than add a security vulnerability.

**Comment by rtkaratekid** [comment]
Why is this not merged? It's a simple PR that works.

**Comment by karelbilek** [comment]
Is this gonna be fixed ever?

**Pull request closed without merging**
