### PR TITLE
Fix issue when gitlab return only first 20 migrations

### PR DESCRIPTION
**Pull request by mef13**
It's duplicate PR #379 that looks dead.
This PR more clear and small.

### CODE REVIEW

**Review by dhui — APPROVED** [review]
Will merge once CI is working again

**Comment by mef13** [comment]
> Will merge once CI is working again

what happened with CI?

**Comment by dhui** [comment]
We need to move to another CI provider since TravisCI stopped providing free builds for open source projects. See also: https://github.com/golang-migrate/migrate/issues/252#issuecomment-747206381

**Comment by dhui** [comment]
@mef13 Can you close and reopen this PR? For some reason, the CircleCI Github checks aren't running...

**Comment by mef13** [comment]
ok

**Pull request closed without merging**
