### PR TITLE
add tests for scylladb. add scylladb to docs

### PR DESCRIPTION
**Pull request by mkorolyov**
Migrate works with Cassandra so it should work with ScyllaDB too as it is a drop-in replacement.

I've checked this and all works fine. Added Cassandra like tests for ScyllaDB and updated docs.

### CODE REVIEW

**Comment by mkorolyov** [comment]
@Fontinalis Hey, could you pls take a look into this one?

**Comment by guy9** [comment]
I'm also interested in this

**Comment by mixellent** [comment]
+1

**Comment by annastuchlik** [comment]
+1

**Review by Fontinalis — APPROVED** [review]
Looks good, thank you for the contribution!

**Pull request merged**
