### PR TITLE
hotfix(dependency): resolve clickhouse dependency breaking changes

### LINKED ISSUE #302: failed on go1.13
**Describe the Bug**
```
>>> go get -u -d github.com/golang-migrate/migrate/cmd/migrate
go: finding github.com/golang-migrate/migrate/cmd/migrate latest
go: finding github.com/golang-migrate/migrate/cmd latest
go get github.com/golang-migrate/migrate/cmd/migrate: module github.com/golang-migrate/migrate@upgrade (v3.5.4+incompatible) found, but does not contain package github.com/golang-migrate/migrate/cmd/migrate
```

**Steps to Reproduce**
my environment:
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myname/Library/Caches/go-build"
GOENV="/Users/myname/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="*.mycompany.com"
GONOSUMDB="*.mycompany.com"
GOOS="darwin"
GOPATH="/Users/haowen/.gvm/pkgsets/go1.13/global"
GOPRIVATE="*.mycompany.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/mycompany/.gvm/gos/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/mycompany/.gvm/gos/go1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h1/9ltt1sp94_x8yzjxjjw5ppbr0000gp/T/go-build058717330=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Expected Behavior**
get repo successful

### PR DESCRIPTION
**Pull request by bxcodec**
fix #302 

What I've done:
- Change the click house package
- Run go mod tidy

### CODE REVIEW

**Comment by FelixSeptem** [comment]
hope to merge this PR ASAP @dhui

**Comment by stanleynguyen** [comment]
@dhui Is a patch with this fix gonna be release soon? We're waiting for it to fix our build

**Comment by bxcodec** [comment]
Notes:

If this PR is not released yet, use the master version when doing `go get`

```
go get -tags 'postgres' -u github.com/golang-migrate/migrate/v4/cmd/migrate@master
```

**Comment by dhui** [comment]
Released [v4.7.1](https://github.com/golang-migrate/migrate/releases/tag/v4.7.1)

**Pull request merged**
