### PR TITLE
Fix go.sum

### LINKED ISSUE #138: github.com/docker/docker checksum mismatch
**Describe the Bug**
I'm using your package in my project together with `go modules`. Since today (this wasn't happening before) I'm struggling with issue related to `github.com/docker/docker` checksum. Looks like in your go.sum file there is a wrong checksum for that dependency.

**Steps to Reproduce**
1. Run "go mod download"

**Stacktrace**
```go: verifying github.com/docker/docker@v0.7.3-0.20180221142240-453f2b8b40b9: checksum mismatch
downloaded: h1:T9/p6Tf8lgB+fBZRwUCn1/b0w8w2/xT2Lsi6SPVp7OU=
go.sum:     h1:j5P9Aya3JMe0sv7rAfRWIohQVP3YxHgui125drv1DAM=
```

### PR DESCRIPTION
**Pull request by fsouza**
See golang/go#29278.
Fix #138.

### CODE REVIEW

**Comment by dhui** [comment]
`go version go1.11.4 linux/amd64`
Builds are failing due to the invalid checksum: https://travis-ci.org/golang-migrate/migrate/jobs/469750108

**Comment by dhui** [comment]
Not sure if the checksums are failing due to the TravisCI build cache. However, I've cleared my module cache locally and rebuilt `migrate` and still have the same `docker/docker` checksum, so the TravisCI build cache is unlikely to be the issue.

**Comment by fsouza** [comment]
Oh noo, I can't reproduce with a clean setup :(((

```
$ docker run -v $PWD:/code -w /code -it golang:1.11 make test COVERAGE_DIR=/tmp/coverage
```

Output here: https://gist.github.com/fsouza/f8fba9869dbd0ee0add12ce1b2897d06

I'll investigate this later today or some time tomorrow. Thanks for the feedback and sorry about the noise!

**Comment by fsouza** [comment]
@dhui it does look like it may be a caching issue with Travis. I enabled Travis on my fork and go was able to download ``github.com/docker/docker``: https://travis-ci.org/fsouza/migrate/jobs/469813717

An easy "fix" would be to update docker/docker to a newer version and see if the test suite stills passes, this would avoid caching issues that other people may face. We could pin it to the [commit](https://github.com/moby/moby/commit/a3efeaad529b945ce5af78c4b08a6ed47399f8d5) right after the current one or we could try to get the latest master and see if everything still works. What do you think?

**Comment by dhui** [comment]
Updating docker to a newer released version to get around this issue sounds good. We're due for an update anyways...
It's unclear to me if we need to use `docker/docker` or `docker/engine` to pin to a release.

**Comment by fsouza** [comment]
@dhui yeah unfortunately after moving from docker/docker to moby/moby, the Docker team stopped tagging that repo, so we have to keep picking a commit :(

I pinned it to https://github.com/moby/moby/commit/b6242da4ee29d7692dec32a5e00fd50b7c886d75. This should be good for review now.

**Comment by dhui** [comment]
I'd rather avoid picking a commit and use tagged releases. That way, it's clear what version of a dependency we're using.

**Comment by dhui** [comment]
Try [docker/engine](https://github.com/docker/engine)

**Comment by fsouza** [comment]
It's not possible to import github.com/docker/engine in the code, so this would require a replace in ``go.mod`` (I think):

```
replace github.com/docker/docker => github.com/docker/engine
```

I can do it, but it's very ugly :) Let me know what you think.

**Comment by dhui** [comment]
What are the issues you encountered when importing `github.com/docker/engine`?
I believe that `migrate` cannot use the `replace` directive since the directive is [only used by the main module](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive). e.g. migrate is used both as a CLI and a library

**Comment by fsouza** [comment]
@dhui https://github.com/docker/engine/blob/170ed8d7e732adabe9b452a9a52c7a104ef2b8ec/api/types/container/config.go#L1

**Comment by dhui** [comment]
> @dhui https://github.com/docker/engine/blob/170ed8d7e732adabe9b452a9a52c7a104ef2b8ec/api/types/container/config.go#L1

Oi... Thanks for investigating! In that case, let's stick with the docker/docker import and use commits which correspond to a release tag in docker/engine.
We can start with commit `f5749085e9cb0565afe342e73a67631f97547054` which corresponds to tag `v18.09.0`, but if that has issues, we can use older versions (unless you wanna try to fix any issues that arise)

**Comment by fsouza** [comment]
Yeah, unfortunately that commit is not in the tree referenced by master on docker/docker :( It's available only on [docker/engine's 18.09 branch tree](https://github.com/docker/engine/tree/18.09) :(

``docker/docker@master`` fails because that's requesting API version 1.40 which isn't released yet, so I pinned to the version that's using API 1.39.

**Comment by dhui** [comment]
Weird, the [docs](https://docs.docker.com/develop/sdk/#api-version-matrix) say that `v18.09` supports API `v1.30`.

Next version to try would be `v18.06.1-ce` which is commit: `320063a2ad06a1d8ada61c94c29dbe44e2d87473`

**Comment by fsouza** [comment]
Sorry, this strategy isn't gonna work.  The tags on docker/engine point to commits that do not exist on docker/docker's tree (though GitHub can render them under docker/docker because docker/engine is a fork).

As an alternative, I tried ``github.com/docker/docker@master`` but that didn't work because it's too far ahead, so I dug the commit history and picked the [commit for ``1.39``](https://github.com/moby/moby/commit/b6242da4ee29d7692dec32a5e00fd50b7c886d75), and that's what this PR is using.

**Comment by dhui** [comment]
> Sorry, this strategy isn't gonna work. The tags on docker/engine point to commits that do not exist on docker/docker's tree (though GitHub can render them under docker/docker because docker/engine is a fork).

Oh, I thought `docker/engine` was a normal fork of `docker/docker`. I didn't realize that the commits were re-written...

As mentioned earlier, I'd rather not pin to arbitrary commit. I'm not familiar enough with the docker package to know which commits are considered stable (e.g. not an alpha/beta/RC release) and don't have a backwards incompatible changes. It'd also be unclear which commit to use for minor bug fixes.

Given the state of the docker/docker package, I think it's better postpone upgrading docker/docker.

I've also figured out the issue I was having with the checksum being being regenerated correctly locally. Earlier, I was using Go 1.11.3 instead of Go 1.11.4... I've now updated to Go 1.11.4 and regenerated `go.sum` in this commit: 24176463f427e9ba6be9c99effb08f3c67d748cf

Thanks again @fsouza for all of the work you've put in to resolving this issue!

**Comment by fsouza** [comment]
Sounds good. Thanks for the feedback and sorry about the back and forth! :)

**Pull request closed without merging**
