### PR TITLE
fix example of install by go toolchain at README

### PR DESCRIPTION
**Pull request by stobita**
Currently, result of install by go toolchain as follows

```bash
> go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
go: finding github.com/golang-migrate/migrate/cmd/migrate latest
go: finding github.com/golang-migrate/migrate/cmd latest
go get github.com/golang-migrate/migrate/cmd/migrate: no matching versions for query "latest"
```

So, I fixed Installation->With Go toolchain.

### CODE REVIEW

**Comment by stobita** [comment]
Thank you for your reply and confirmation.
The version of Golang I am using is 1.12.7.

```bash
~ > go version
go version go1.12.7 darwin/amd64
~ > go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
go: finding github.com/golang-migrate/migrate/cmd/migrate latest
go: finding github.com/golang-migrate/migrate/cmd latest
go get github.com/golang-migrate/migrate/cmd/migrate: no matching versions for query "latest"
```

**Comment by dhui** [comment]
Are you running `go get` in your `$GOPATH`?

**Comment by stobita** [comment]
No. I'm running outside $GOPATH.

**Comment by dhui** [comment]
Try running `go clean -modcache` and then `go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate`

**Comment by stobita** [comment]
I ran as you said. But the result was the same.

```
~ > go clean -modcache
~ > go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
go: finding github.com/golang-migrate/migrate/cmd/migrate latest
go: finding github.com/golang-migrate/migrate/cmd latest
go: finding github.com/golang-migrate/migrate v3.5.4+incompatible
go: downloading github.com/golang-migrate/migrate v3.5.4+incompatible
go: extracting github.com/golang-migrate/migrate v3.5.4+incompatible
go get github.com/golang-migrate/migrate/cmd/migrate: no matching versions for query "latest"
```

**Comment by dhui** [comment]
Weird, based on your the output, it looks like you're pulling migrate v3 instead of migrate v4. I don't think modules are enabled. Try setting `GO111MODULE=on`.

https://github.com/golang/go/wiki/Modules#how-to-use-modules

**Comment by stobita** [comment]
Already GO111MODULE=on was.

```bash
~ > echo $GO111MODULE
on
~ > go clean -modcache
~ > go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
go: finding github.com/golang-migrate/migrate/cmd/migrate latest
go: finding github.com/golang-migrate/migrate/cmd latest
go: finding github.com/golang-migrate/migrate v3.5.4+incompatible
go: downloading github.com/golang-migrate/migrate v3.5.4+incompatible
go: extracting github.com/golang-migrate/migrate v3.5.4+incompatible
go get github.com/golang-migrate/migrate/cmd/migrate: no matching versions for query "latest"
```

**Comment by incazteca** [comment]
Can confirm same issue in go 1.12.9. Specifying v4 works

**Comment by dhui** [comment]
@incazteca @stobita Can you reproduce the issue in a docker container? That way we're isolating environment differences.

**Comment by incazteca** [comment]
@dhui Not really familiar with Dockerfile writing but I think I found a way to reproduce this, will provide a dockerfile later when I have the time. For now I noticed that the issue happens when a go.mod file is present. I've also noticed that when the command does work it downloads the latest version 3

**Comment by denisdubovitskiy** [comment]
I've encountered with the same problem.

Here is the workaround:
`go get -tags 'postgres' -u github.com/golang-migrate/migrate/v4/cmd/migrate/`

Can anyone please update the documentation?

**Comment by Houndie** [comment]
Confirming this is still an issue with go1.14.2

**Comment by Matt3o12** [comment]
@dhui If you're still trying to troubleshoot this issue, I created a dockerfile that represents my environment close enough to also cause this failure. Be warned that the docker image it with the dependencies is kind of big (between 500MB-1GB I think).

```Dockerfile

FROM fedora:32

RUN dnf update -y && dnf install golang git -y

RUN mkdir /golang && mkdir /develop && cd /develop && git clone https://github.com/moul/golang-repo-template.git myrepo

ENV GOPATH=/golang
WORKDIR /develop/myrepo


RUN go build . && ./golang-repo-template
RUN go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
```

**Comment by dhui** [comment]
Thanks for the reproducible `Dockerfile` @Matt3o12 !

I *think* I've figured out the issue. It looks like there are issues installing `migrate`from within a module. e.g. a project with a `go.mod` file

This failure might be an issue specific to `migrate` since we opted into modules without a major version change in [v3.5.2](https://github.com/golang-migrate/migrate/releases/tag/v3.5.2) and later opted out in [v3.5.3](https://github.com/golang-migrate/migrate/releases/tag/v3.5.3)

To work around this issue, you can either:
1. Change your working directory before running `go get` so you're not installing within a Go module. e.g. `WORKDIR /`
1. Or disable modules before running `go get`. e.g. `ENV GO111MODULE=off`
1. Install using `RUN go get -tags 'postgres' -u github.com/golang-migrate/migrate/v4/cmd/migrate`
    * Not recommended since this can modify your project's `go.mod` file. See: https://github.com/golang/go/issues/30515

I'll update the README to warn about installing from an existing module.

**Comment by dhui** [comment]
Note: in Go 1.16, it seems like `go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest` is the way to go.

**Pull request closed without merging**
