### PR TITLE
Adding support clickhouse cluster

### PR DESCRIPTION
**Pull request by preved911**
Hello. I would like to create cluster wide `schema_migrations` table, when I run migrations on clusterized clickhouse. As I think, It's will guarante that new migrations may be executed on any node of cluster.

### CODE REVIEW

**Review by dhui — CHANGES_REQUESTED** [review]
For my future reference: [clickhouse distributed ddl docs](https://clickhouse.tech/docs/en/sql-reference/distributed-ddl/)

Overall, this change LGTM. Keep in mind that you may have issues if migrations are run simultaneously on different machines since the clickhouse db driver doesn't use a distributed lock.

Can you add tests or is it not possible to setup a cluster in docker?

**Comment by preved911** [comment]
> Can you add tests or is it not possible to setup a cluster in docker?

@dhui, for me its look like too hard. I viewed realized tests in project and can't imagine how to do that in such flow. For replicate tables over clickhouse nodes, we have to up 2 or more clickhouse nodes with customized config file(need zookeeper instance address specify). [dktest](github.com/dhui/dktest), if I undestand correct, do not allow to mount volumes into declared containers. So, should I create very custom test for this case?

**Comment by dhui** [comment]
Yeah, I don't think it's a trivial amount of work to run multiple containers & images on the same network so we can test a clickhouse cluster setup.

I'd love to have integration tests for clickhouse clusters, but if it's not feasible, we can add a caveat in the docs stating that clickhouse clusters aren't officially supported since there aren't any tests.

**Comment by preved911** [comment]
@dhui, I added notes in README.md. Did you mean it?

**Comment by preved911** [comment]
@dhui, so can it be merged?

**Review by dhui — APPROVED** [review]
Sorry for the delay and thanks again for the PR!

**Pull request merged**
