### PR TITLE
Use http.FileSystem for all the things

### PR DESCRIPTION
**Pull request by solderjs**
This shows how it's possible to use http.FileSystem for:

* file
* packr
* fileb0x
* wedav
* almost every other thing that works at all like a file system

### CODE REVIEW

**Comment by coolaj86** [comment]
It looks like the build is failing due to Cassandra, not necessarily this change.

I’ve been able to use it locally in a project and it works as expected.

How would I be able to tell?

**Comment by coolaj86** [comment]
@dhui 

> Add tests

I ran tests locally. Adding my own tests won't prevent the existing tests from failing.

> Please address the issues I've raised here.

This PR is a direct response to those issues. Please take a look at the code. The purpose of the code is to illustrate that by using Go's http.FileSystem` interface you support almost every file module that exists - including Packr.

WebDAV, the network transfer protocol, is not useful for this. However, the `webdav.FileSystem`, from the official Go package, much like `http.FileSystem` is an interface that is used by many packages.

**Comment by dhui** [comment]
We need tests for each source driver. Relying on existing tests to catch issues is not sufficient since we need to know if the driver we're depending on works or breaks with an update.

> The purpose of the code is to illustrate that by using Go's http.FileSystem` interface you support almost every file module that exists - including Packr.

Ahh, I see now!
I like how using interfaces reduces the need for custom source driver code, but I'm not a fan of the new split logic in the file source driver. It would be cleaner to implement a source driver(s) that only consumes certain interfaces (e.g. named `source.HttpFS` and `source.webdavFS`) and re-implement `source.File` to use `source.HttpFS`.
Source drivers would still need to be registered but can be registered at the top level. e.g. we won't need to use "sub-drivers"

Are you familiar with other FS interfaces? I find it odd to use an FS interface from the `http` package since some of the FS won't the associated with HTTP. I did a cursory search for other FS interfaces but didn't find another built-in one. I also found [this](https://talks.golang.org/2012/10things.slide#8), but it's not a built-in interface so fewer packages are likely to implement it.

**Comment by mikijov** [comment]
I would like to encourage you two somehow resolve this. http.Filesystem is the de-facto standard. You should not really look at it as http. It really relies on os.File interface really, but it limits it down to only few functions. It was first used in web world, so that's why http, but since it has been used in many other projects. The real reason for me adding a vote here is that I too want to use esc since go-binddata is deprecated. So just like @smacker in his lookout project, I would very much like to see support for esc or better, support for any provider of http.Filesystem interface.

**Comment by dhui** [comment]
To be clear, using the `http.FileSystem` is not a blocker for the PR. My previous comment was purely exploratory in nature.

The blockers for this PR are:
1. Merge conflicts
1. Code cleanup/refactor - The file source driver should rely on the shared/base `http.FileSystem` source driver "implementation" which should also be used by other source drivers.
1. New source drivers should have tests for basic functionality

I don't have the bandwidth to make these changes myself, so feel free to open a PR to resolve the blockers mentioned above.

**Comment by dhui** [comment]
@mikijov Thanks for providing background on how `http.FileSystem` came to be

**Comment by coolaj86** [comment]
I want to do another PR with the requested changes, but I haven't had the time and so I've just been using my own fork.

However, I don't intend to maintain a fork long-term.

**Comment by maxekman** [comment]
Any update on this? Would love to see it merged to enable the use all the different `http.FileSystem`-compatible libs!

**Comment by wayneashleyberry** [comment]
Anything I can help with here? I'd really love to get this in as well 🤞

**Comment by dhui** [comment]
Closed in favor of https://github.com/golang-migrate/migrate/pull/293

**Pull request closed without merging**
